# Generated by Django 4.1.2 on 2022-10-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_osoba_data_dodania'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=50)),
                ('kraj', models.CharField(choices=[('PL', 'Polska'), ('DE', 'Niemcy'), ('US', 'Stany Zjednoczone'), ('FR', 'Francja')], default='PL', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
        migrations.AddField(
            model_name='osoba',
            name='druzyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.druzyna'),
        ),
    ]
